name: Publicando imagen para User-srv (Tarea4, Respuesta_1)


# evento
on: [push]

# jobs
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # esto se configura
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: maguilf/labcna-user
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./users-svc
          file: ./users-svc/Dockerfile
          push: true
          tag_semver: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      #ERROR: unable to prepare context: path "./users-srv" not found  
      #Error: buildx failed with: ERROR: unable to prepare context: path "./users-srv" not found
